import { Concept, Region } from '@/types';

// Sample cooking concepts for different cuisines
export const sampleConcepts: Concept[] = [
  {
    id: 'concept-1',
    title: 'Basic Kitchen Safety',
    description: 'Learn essential safety rules for cooking',
    region: 'region-1',
    order: 1,
    unlocked: true,
    completed: false,
    videos: [
      {
        id: 'video-1-1',
        title: 'Introduction to Kitchen Safety',
        url: 'https://youtu.be/50q8wD6MXgI?si=3tx9xlJt6LSNAdyu',
        watched: false,
        order: 1,
      },
      {
        id: 'video-1-2',
        title: 'Handling Knives Safely',
        url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
        watched: false,
        order: 2,
      },
      {
        id: 'video-1-3',
        title: 'Fire Safety in the Kitchen',
        url: 'https://www.youtube.com/watch?v=M7lc1UVf-VE',
        watched: false,
        order: 3,
      },
    ],
    quiz: {
      id: 'quiz-1',
      passingScore: 70,
      questions: [
        {
          id: 'q1-1',
          question: 'What should you do before handling food?',
          options: ['Wash hands', 'Check phone', 'Turn on TV', 'Skip preparation'],
          correctAnswer: 0,
          explanation: 'Always wash your hands before handling food to prevent contamination.',
        },
        {
          id: 'q1-2',
          question: 'How should you hold a knife?',
          options: ['By the blade', 'By the handle', 'With bare hands', 'Any way'],
          correctAnswer: 1,
          explanation: 'Always hold a knife by its handle, never by the blade.',
        },
      ],
    },
    googleDocsLink: 'https://docs.google.com/document/d/example1',
    googleSitesLink: 'https://sites.google.com/view/example1',
  },
  {
    id: 'concept-2',
    title: 'Indian Spices & Flavors',
    description: 'Discover the magic of Indian spices',
    region: 'region-1',
    order: 2,
    unlocked: false,
    completed: false,
    videos: [
      {
        id: 'video-2-1',
        title: 'Introduction to Indian Spices',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 1,
      },
      {
        id: 'video-2-2',
        title: 'Common Spice Combinations',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 2,
      },
      {
        id: 'video-2-3',
        title: 'Spice Storage & Freshness',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 3,
      },
      {
        id: 'video-2-4',
        title: 'Making Basic Masala',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 4,
      },
    ],
    quiz: {
      id: 'quiz-2',
      passingScore: 70,
      questions: [
        {
          id: 'q2-1',
          question: 'What is turmeric commonly used for?',
          options: ['Sweetness', 'Color and flavor', 'Thickness', 'Cooling'],
          correctAnswer: 1,
          explanation: 'Turmeric adds both color and flavor to dishes.',
        },
      ],
    },
    googleDocsLink: 'https://docs.google.com/document/d/example2',
    googleSitesLink: 'https://sites.google.com/view/example2',
  },
  {
    id: 'concept-3',
    title: 'Italian Pasta Basics',
    description: 'Master the art of pasta cooking',
    region: 'region-2',
    order: 3,
    unlocked: false,
    completed: false,
    videos: [
      {
        id: 'video-3-1',
        title: 'Types of Pasta',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 1,
      },
      {
        id: 'video-3-2',
        title: 'Cooking Perfect Pasta',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 2,
      },
      {
        id: 'video-3-3',
        title: 'Basic Pasta Sauces',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 3,
      },
    ],
    quiz: {
      id: 'quiz-3',
      passingScore: 70,
      questions: [
        {
          id: 'q3-1',
          question: 'How do you know pasta is done?',
          options: ['It floats', 'It is al dente', 'It dissolves', 'Color changes'],
          correctAnswer: 1,
          explanation: 'Pasta should be al dente - tender but firm to bite.',
        },
      ],
    },
    googleDocsLink: 'https://docs.google.com/document/d/example3',
    googleSitesLink: 'https://sites.google.com/view/example3',
  },
  {
    id: 'concept-4',
    title: 'Balanced Nutrition',
    description: 'Understanding nutrients and healthy eating',
    region: 'region-3',
    order: 4,
    unlocked: false,
    completed: false,
    videos: [
      {
        id: 'video-4-1',
        title: 'What is Nutrition?',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 1,
      },
      {
        id: 'video-4-2',
        title: 'The Food Groups',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 2,
      },
      {
        id: 'video-4-3',
        title: 'Portion Sizes',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        watched: false,
        order: 3,
      },
    ],
    quiz: {
      id: 'quiz-4',
      passingScore: 70,
      questions: [
        {
          id: 'q4-1',
          question: 'Why is protein important?',
          options: ['For energy', 'For building muscles', 'For taste', 'For color'],
          correctAnswer: 1,
          explanation: 'Protein is essential for building and repairing muscles.',
        },
      ],
    },
    googleDocsLink: 'https://docs.google.com/document/d/example4',
    googleSitesLink: 'https://sites.google.com/view/example4',
  },
];

export const sampleRegions: Region[] = [
  {
    id: 'region-1',
    name: 'safety-garden',
    displayName: 'Safety Garden',
    color: '#22c55e',
    position: { x: 20, y: 30 },
    unlocked: true,
    concepts: sampleConcepts.filter((c) => c.region === 'region-1'),
    icon: '🛡️',
  },
  {
    id: 'region-2',
    name: 'flavor-forest',
    displayName: 'Flavor Forest',
    color: '#f59e0b',
    position: { x: 50, y: 20 },
    unlocked: false,
    concepts: sampleConcepts.filter((c) => c.region === 'region-2'),
    icon: '🌳',
  },
  {
    id: 'region-3',
    name: 'nutrition-meadow',
    displayName: 'Nutrition Meadow',
    color: '#3b82f6',
    position: { x: 80, y: 60 },
    unlocked: false,
    concepts: sampleConcepts.filter((c) => c.region === 'region-3'),
    icon: '🌿',
  },
];

